version: "3"
services:
    server:
        image: golang:1.21
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        ports:
            - 8080:8080
        environment:
            - CGO_ENABLED=1
        command: go run server.go
